spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
redis:
              port: 6379
              host: 192.168.199.129
server:
  port: 8888
  servlet:
    context-path: /demo
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.oaec.sprngbootmybatisplus1.entity
  mapper-locations: classpath:/mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hadron.cachedemo.entity
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
logging:
  level:
    com.hadron.cachedemo: trace
